### ISSUE TITLE
Make install: Nothing to be done. 

### ISSUE THREAD

**Issue by david0rk** [VirusTotal/qt-virustotal-uploader#4]
Building on xubuntu 16.04
Following build instructions as per Readme.md 

with one minor change:  qmake -qt5  instead of qmake 
(otherwise  qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory) 

sudo make install
make: Nothing to be done for 'install'.

trying to run the built executable

 $ ./VirusTotalUploader 
./VirusTotalUploader: error while loading shared libraries: libcvtapi.so.1: cannot open shared object file: No such file or directory 

however /usr/local/lib/libcvtapi.so.1 exists, so the c-vtapi does seem to have installed correctly.

$ LD_PRELOAD=/usr/local/lib/libcvtapi.so.1 ./VirusTotalUploader   does launch the utility.

This is probably a *buntu specific issue.

**Comment by karlhiramoto** [comment]
If you think this would help I can add it to the readme.

```
sudo apt-get install build-essential qtchooser qt5-default libjansson-dev libcurl4-openssl-dev git
git clone https://github.com/VirusTotal/c-vtapi.git
cd c-vtapi
./conigure && make -j4 
sudo make install
sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/usr-local-lib.conf'
sudo ldconfig
cd ..
git clone https://github.com/VirusTotal/qt-virustotal-uploader.git
cd qt-virustotal-uploader
qtchooser -run-tool=qmake -qt=5
make -j4

#optionally install 
sudo make install

```

**Comment by karlhiramoto** [comment]
updated readme in  5ef9e18

**Comment by david0rk** [comment]
Awesome, thanks for the quick response. After looking into it a bit, this is a *buntu specific thing because of multiarch support and how the break libs into x86 and x86_64 .
